RCPS-162 stud-info-mgt-app: EDITUSER-Save button should be disabled i…
RoCS2024/student-info-mgt-app pull request #23
Opened 2024-05-02 01:33 UTC by Conconrad

Description

Defect Description: save button is not disabled when other fields are null. and it accepts empty field does not also display  “All fields are important. Please enter valid input.“

Environment:

OS: Windows/Linus/Mac

System: Laptop/Desktop

Priority: High

Severity: High

Steps to Reproduced:

Open Intellij application

Run the code

leave all fields null.

Expected Result: disable the save button and display “All fields are important. Please enter valid input.“ fields should only accept alpha-numeric characters only.

Actual Result: The system accepts wrong input and does not display “All fields are important. Please enter valid input.“

2024-05-02 02:06 UTC, Conconrad commented
RCPS-158 stud-info-mgt-app: EDITUSER-updating username

Defect Description: I tried changing the username but it does not change. 

Environment:

OS: Windows/Linus/Mac

System: Laptop/Desktop

Priority: High

Severity: High

Steps to Reproduced:

Open Intellij application

Run the code

Edit Username

Expected Result: update the username, and display “Please enter valid input“ when entering invalid input. 

Actual Result: The system accepts wrong input and does not display “Please enter valid input“.

2024-05-02 03:59 UTC, zhairanicolepacheco commented on src/main/java/com/student/user/app/controllers/item/ChangePswController.java
> +        usernameField.setEditable(false);
what is the usage of this? is this necessary?

2024-05-02 04:27 UTC, zhairanicolepacheco requested changes
see comment

2024-05-03 10:19 UTC, zhairanicolepacheco approved these changes

2024-05-03 12:59 UTC, merged