RCPS-144: stud-info-mgt-app: Even if you don't enter any information…
RoCS2024/student-info-mgt-app pull request #6
Opened 2024-04-28 03:43 UTC by jshrq

…, anyone can log in.

2024-04-28 11:03 UTC, RoCS2024 commented on src/main/java/com/student/user/app/controllers/item/AddStudentController.java
> +    private StudentFacade studentFacade = new StudentFacadeImpl(new StudentDaoImpl());
Daos should not be visible in UI

2024-04-28 11:03 UTC, RoCS2024 commented on src/main/java/com/student/user/app/controllers/item/UpdateStudentController.java
> +    private StudentFacade studentFacade = new StudentFacadeImpl(new StudentDaoImpl());
Daos should not be visible in UI

2024-04-28 11:04 UTC, RoCS2024 commented on src/main/java/com/student/user/app/controllers/main/MainController.java
> +//    public void logButtonOnAction(ActionEvent event) throws IOException {
why comment?

2024-04-28 11:04 UTC, RoCS2024 requested changes
see comments

2024-04-28 17:42 UTC, jshrq commented
> see comments

all done sir!

2024-04-30 00:28 UTC, zhairanicolepacheco approved these changes

2024-04-30 04:11 UTC, RoCS2024 approved these changes

2024-04-30 04:42 UTC, merged